# Generated by Django 4.1.1 on 2022-09-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0002_qq"),
    ]

    operations = [
        migrations.DeleteModel(name="QQ",),
    ]
