# Generated by Django 4.1.1 on 2022-09-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0003_delete_qq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=10000)),
                ("uuid", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(name="Dummy",),
    ]
